### ISSUE TITLE
purpose of routine assignment?

### ISSUE THREAD

**Issue by ritjoe** [ritjoe/hfoss#371]
Given that I'm the sole instructor on this instance of the HFOSS course, and the project rests within my account such that my responsibility for it is pretty clear, I'm fine with approaching every issue and pull request here as being implicitly, de facto assigned to me.

Currently, I receive ritjoe/hfoss-related email directly to my inbox, so that I can see it as soon as I check my mail. It isn't the only thing I receive that way, but so far it retains a fairly privileged position in my incoming mail stream. My usual approach when traffic gets to a certain volume is to create a filter which will file it automatically on receipt into its own mail folder. When that happens, it becomes much easier to pass over and check only on occasion. 

My question then is, is there any benefit to explicitly assigning anything to me? Is anyone getting repeated reminder notifications about unassigned PRs and issues which then stop once an issue is assigned? 

If so, and those reminders are seen as a problem in need of resolution, I'd be happy to see if there is some way to set an automatic assignment to me, or even to continue to receive assignments (and thus assignment notifications).

On the other hand, without a clear reason to make an explicit assignment, I'd be *very* happy to leave these unassigned, with the understanding as above that I'm the implicit, de facto assignee. An explicit action to assign them to me, from my perspective, tells me nothing new, since I am notified of actions on PRs and issues anyway and assume I'll need to address them at some point. What's more, they generate a flood of traffic exactly at times in which I have pending items to attend to, which notifications I then have to sort through in order to find more informative messages.

If there's a benefit to making the assignment, I'm open to hearing it. Otherwise, I'd ask that we limit most non-instructor actions to reviews and comments, which have been and probably will remain uniquely valuable.

(I started on a bit of a side discussion about how assignments as handled here are more-or-less proprietary to GitHub and not readily forkable. I think this is an important facet of this question on whether and how to embrace assignments, but I'm not sure we're ready to have that broader discussion right here, right now, especially given some of the passion it has generated in the past.)

**Comment by jflory7** [comment]
Just to add context even though the issue is closed, this was mostly an action being done to correctly update the metadata for a hypothetical, future sorting and searching in the event, which would ideally be helpful if there was another professor teaching the course, and the issues / PRs handled by that professor were in the same repository. However, this isn't inside the FOSSRIT org, so this point is mostly irrelevant here.

I wasn't aware that emails were generated for the assignment, so I hadn't seen it as an issue. But now that I know it generates noise for assignments, I'll refrain from assigning issues to you since I can see now how that would obviously be annoying and make it more difficult to process valuable emails from trivial emails.
