### ISSUE TITLE
Migrate to wikis or another platform from ofCourse

### ISSUE THREAD

**Issue by axk4545** [ritjoe/hfoss#491]
Opening this issue to help @ritjoe track progress moving the course website off of the ofCourse platform and request assistance from other with this process if needed. If this is unneeded please close.

**Comment by ReginaTL** [comment]
Alternatively if you want to be able to do pull requests to the wiki: http://www.growingwiththeweb.com/2016/07/enabling-pull-requests-on-github-wikis.html
Which basically makes another repo for the wiki that is then automated to update the actual wiki.

Otherwise people just generally just update the wiki on there own fork and then make an issue/contact the maintainer to copy and paste the changes in manually.

**Comment by ritjoe** [comment]
I do have [a public repository](https://github.com/ritjoe/hfoss-wiki) for the wiki contents, have set it as a remote from my working copy of the repo, and do try to keep it updated. Issues and PRs can be filed against it.

**Comment by ritjoe** [comment]
Little bit of an update.  Through my previous run of the course in Spring 2018, I added material to the [course wiki](https://github.com/ritjoe/hfoss/wiki) instead of putting it in that semester's ofcourse instance. 

This strikes some middle ground between avoiding further support for dependency on GitHub's proprietary components on the one hand, which is an ongoing goal of mine, and on the other hand using free software to run the course, since the content in the wiki is (thanks to tools like pandoc et al) portable Markdown, and since the wiki engine itself, Gollum, is free software and can run outside GitHub. 

One challenge though is that the wiki itself does not accept binary assets, like images or various binary document formats (PDFs, OpenOffice, etc). One can include a link to an asset held elsewhere, though, and so I've been putting those in the [assets directory of the main course repo](https://github.com/ritjoe/hfoss/tree/master/assets)

Another challenge is the one to which @gen1e has pointed to a solution, which is, the wiki is not directly open to PRs. That solution requires me to use CI, which I have been hesitant to embrace, but which I'm now open to exploring. I'll address that in a new issue.

What I most want to preserve is the central workflow of student-submitted PRs for changes to the Participants section of any given semester's instance of [ofcourse](https://github.com/ryansb/ofcourse).   

Whether we do that through the wiki, through a repurposing of [foss-profiles](https://github.com/FOSSRIT/foss-profiles), through GitHub pages attached to this repo or through a free-standing Jekyll implementation (as in the work @ctmartin , I don't know. I'm considering closing this issue in favor of something more specifc, but will leave it open for now to see if anyone has further comment or suggestions.

**Comment by ritjoe** [comment]
Current discussion in HFOSS today is about the spotty performance of the blog post counter function.

I'm perfectly content for that to be part of this discussion in terms of why we might want to migrate to something. I'm also happy with the idea that someone open issues on this repo or on upstream (eg ryansb/ofCourse#41) to document and improve or remove this function.

**Comment by ritjoe** [comment]
One way I could see this working is if someone was able to test ofcourse against some set reasonably extensive set of blogging platforms that we would then target with updates, test against, recommend to downstream users and learners, etc.

**Comment by ritjoe** [comment]
[Ugh. Something seems to have gone amiss with my big comment upthread--it's garbled near the end.

Will look to see if there's an email version of it in my `sent` folder to see what I meant it to say there at the bottom.]

In the meantime, I'd like to point out that @ct-martin has worked to make presenting the non-wiki course content viable in Jekyll:

https://github.com/ct-martin/hfoss.rocfoss.org

**Comment by ritjoe** [comment]
This issue remains. 

Of further relevance to the discussion is that I added a student journals this semester. Students are meant to write several times a week, in Markdown or similar markup language, to commit that writing to a local working tree, and to push those commits to a repository on the institution's internally-hosted Gitlab instance. Only the student and instructor have routine access to the journal repositories to encourage candor, spontaneity, exploration and to reduce inhibitions over fear of failure or exposure. With the pandemic-induced pivot to remote learning the journals became one of several options given students for maintaining asynchronous course-related communication with and feedback to the instructor.

I mention it here because it was a significant foray into using the RIT-hosted Gitlab instance.

Additionally, due to the pandemic, the final project shifted from Sugar Desktop with an option to use Sugarizer, to the more home-friendly [Sugarizer Lite](https://github.com/ritjoe/sugarizer-lite). Since the upstream project and the fork both were hosted on Github this has fewer immediate implications for hosting course content, other than the possibility that Sugarizer being something of a monorepo, if the course were to continue in that direction the fork could be merge with the course content into a monorepo (amongst many other possibilities).
